FROM node:18

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# No need to copy source code - it will be mounted

EXPOSE 4200

CMD ["npm", "start"]
