FROM maven:3.8-openjdk-17

WORKDIR /app

# Copy only pom.xml first
COPY pom.xml .

# Download dependencies
RUN mvn dependency:go-offline

# No need to copy source code - it will be mounted

EXPOSE 8080

CMD ["mvn", "spring-boot:run"]
